install_data('vantage.desktop',
  install_dir : vt_xdg_autostart)

install_data('vantage-wayland.desktop',
  install_dir : join_paths(vt_prefix, get_option('datadir'), 'wayland-sessions'))

install_data('defaults/vantage.conf',
  install_dir : vt_sysconfdir)

install_data('themes/Vantage-Dark/theme.json',
  install_dir : join_paths(vt_datadir, 'themes/Vantage-Dark'))

install_data('themes/Vantage-Light/theme.json',
  install_dir : join_paths(vt_datadir, 'themes/Vantage-Light'))
