vantage_includes = include_directories('.')

install_headers(
  'vantage/vt-core.h',
  'vantage/vt-config.h',
  'vantage/vt-ipc.h',
  'vantage/vt-renderer.h',
  'vantage/vt-gpu.h',
  'vantage/vt-backend.h',
  'vantage/vt-compositor.h',
  'vantage/vt-wm.h',
  'vantage/vt-session.h',
  'vantage/vt-panel.h',
  'vantage/vt-desktop.h',
  'vantage/vt-wallpaper.h',
  'vantage/vt-theme.h',
  'vantage/vt-settings.h',
  'vantage/vt-input.h',
  'vantage/vt-integrations.h',
  'vantage/vt-diagnostics.h',
  subdir : 'vantage-' + vt_api_version,
)
